standard_robot_pp_ros2:
  ros__parameters:
    device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
    set_detector_color: false
    record_rosbag: false
    debug: false

joint_state_publisher:
  ros__parameters:
    use_sim_time: false
    rate: 200
    source_list: ["serial/gimbal_joint_state"]
    offset_timestamp: 0.0

robot_state_publisher:
  ros__parameters:
    use_sim_time: false
    publish_frequency: 200.0
