#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
PB2025 Sentry Strategy Node (Python Version)
Author: PolarBear Team (Generated by AI)
Description: 
    实现了哨兵机器人的核心决策逻辑 (FSM)。
    替代了原本的 behavior_trees/rmul_2025.xml。
    
Features:
    - 4分30秒强制启动机制
    - 简单的状态机逻辑 (感知 -> 决策 -> 执行)
    - 严格兼容原有的 Topic 接口
"""

import math
import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile

# 导入标准消息
from geometry_msgs.msg import Twist, PoseStamped
from example_interfaces.msg import Float32

# 导入自定义消息 (依赖 pb_rm_interfaces)
# 如果本地环境报错，请确保已 source install/setup.bash
try:
    from pb_rm_interfaces.msg import GameStatus, RobotStatus, RfidStatus
except ImportError:
    print("Error: Could not import pb_rm_interfaces. Make sure the package is built and sourced.")
    raise

class SentryStrategyNode(Node):
    def __init__(self):
        super().__init__('pb2025_sentry_strategy_node')

        # ==================== 参数配置 ====================
        self.FORCE_START_TIME_SEC = 270.0  # 4分30秒强制启动
        self.LOOP_RATE_HZ = 10.0           # 控制循环频率
        
        # 阈值配置 (参考 rmul_2025.xml)
        self.HP_MIN = 200        # 血量低于此值进入生存模式
        self.HEAT_MAX = 350      # 热量高于此值停止射击(策略层暂不控制开火，仅作状态判断)
        self.AMMO_MIN = 0        # 弹丸阈值

        # 目标点配置
        self.ATTACK_POSE = (4.65, -3.5, 0.0)  # 进攻点 (x, y, yaw)
        self.SUPPLY_POSE = (0.0, 0.0, 0.0)    # 补给点/安全点

        # ==================== 状态变量 ====================
        self.start_time = self.get_clock().now()
        
        # 数据缓存 (初始化为 None 以区分是否收到过消息)
        self.latest_game_status = None
        self.latest_robot_status = None
        self.latest_rfid_status = None

        # ==================== 通信接口 ====================
        qos = QoSProfile(depth=10)

        # 1. 订阅者 (保持话题名不变)
        self.sub_game = self.create_subscription(
            GameStatus, 'referee/game_status', self.game_status_cb, qos)
        self.sub_robot = self.create_subscription(
            RobotStatus, 'referee/robot_status', self.robot_status_cb, qos)
        self.sub_rfid = self.create_subscription(
            RfidStatus, 'referee/rfid_status', self.rfid_status_cb, qos)

        # 2. 发布者 (保持话题名不变)
        self.pub_vel = self.create_publisher(Twist, 'cmd_vel', qos)
        self.pub_spin = self.create_publisher(Float32, 'cmd_spin', qos)
        self.pub_goal = self.create_publisher(PoseStamped, 'goal_pose', qos)

        # 3. 定时器 (主循环)
        self.timer = self.create_timer(1.0 / self.LOOP_RATE_HZ, self.control_loop)
        
        self.get_logger().info("Sentry Strategy Node (Python) Started. Waiting for Game Start or Timeout...")

    # ==================== 回调函数 ====================
    def game_status_cb(self, msg):
        self.latest_game_status = msg

    def robot_status_cb(self, msg):
        self.latest_robot_status = msg

    def rfid_status_cb(self, msg):
        self.latest_rfid_status = msg

    # ==================== 核心逻辑 ====================
    def control_loop(self):
        """
        主控制循环：感知 -> 决策 -> 执行
        """
        # 1. 检查比赛是否开始
        if not self.is_game_running():
            self.stop_robot()
            return

        # 2. 比赛进行中：基础动作
        # 对应 XML: <PublishSpinSpeed spin_speed="7.0" .../>
        self.publish_spin_speed(7.0)

        # 3. 状态决策
        if self.is_robot_healthy():
            # === 状态良好：进攻/巡逻 ===
            # 对应 XML: <PubNav2Goal goal="4.65;-3.5;0" .../>
            self.get_logger().debug("State: Attack/Patrol", throttle_duration_sec=2.0)
            self.publish_nav_goal(*self.ATTACK_POSE)
        else:
            # === 状态不佳：生存/补给 ===
            self.get_logger().warn("State: Survival/Resupply", throttle_duration_sec=2.0)
            self.execute_survival_logic()

    # ==================== 判断逻辑 ====================
    def is_game_running(self):
        """
        判断比赛是否开始，包含强制启动逻辑
        """
        # 逻辑 A: 时间强制启动
        elapsed = (self.get_clock().now() - self.start_time).nanoseconds / 1e9
        if elapsed > self.FORCE_START_TIME_SEC:
            self.get_logger().info("Force Start Activated (Timeout > 4m30s)", throttle_duration_sec=5.0)
            return True

        # 逻辑 B: 裁判系统数据
        if self.latest_game_status is None:
            return False
        
        # game_progress = 4 代表比赛进行中
        if self.latest_game_status.game_progress == 4:
            return True
            
        return False

    def is_robot_healthy(self):
        """
        判断机器人是否健康 (血量、热量、弹丸)
        对应 XML: check_robot_status -> IsStatusOK
        """
        if self.latest_robot_status is None:
            return True # 默认健康，防止没数据时发呆
        
        s = self.latest_robot_status
        is_hp_ok = s.current_hp >= self.HP_MIN
        is_heat_ok = s.shooter_17mm_1_barrel_heat <= self.HEAT_MAX
        is_ammo_ok = s.projectile_allowance_17mm >= self.AMMO_MIN
        
        return is_hp_ok and is_heat_ok and is_ammo_ok

    def execute_survival_logic(self):
        """
        生存模式逻辑
        对应 XML: check_robot_status -> Fallback (IsRfidDetected or PubNav2Goal)
        """
        # 检查是否已经在补给区 (不重叠区域)
        in_supply_zone = False
        if self.latest_rfid_status:
            # friendly_supply_zone_non_exchange == 1 (DETECTED)
            if self.latest_rfid_status.friendly_supply_zone_non_exchange == 1:
                in_supply_zone = True
        
        if in_supply_zone:
            # 已经在补给区，保持静止或微调
            # 这里为了简单，我们不再发布目标点，或者发当前点，避免干扰补给
            # 原逻辑中如果 IsRfidDetected 成功，就不会执行后面的 PubNav2Goal
            pass 
        else:
            # 不在补给区，前往补给点
            self.publish_nav_goal(*self.SUPPLY_POSE)

    # ==================== 执行动作 ====================
    def stop_robot(self):
        """停止所有运动"""
        self.publish_spin_speed(0.0)
        self.pub_vel.publish(Twist()) # 发送零速度

    def publish_spin_speed(self, speed):
        """发布小陀螺速度"""
        msg = Float32()
        msg.data = float(speed)
        self.pub_spin.publish(msg)

    def publish_nav_goal(self, x, y, yaw):
        """发布导航目标点 (欧拉角转四元数)"""
        msg = PoseStamped()
        msg.header.stamp = self.get_clock().now().to_msg()
        msg.header.frame_id = "map"
        
        msg.pose.position.x = float(x)
        msg.pose.position.y = float(y)
        msg.pose.position.z = 0.0

        # Yaw 转四元数
        cy = math.cos(yaw * 0.5)
        sy = math.sin(yaw * 0.5)
        msg.pose.orientation.w = cy
        msg.pose.orientation.z = sy
        msg.pose.orientation.x = 0.0
        msg.pose.orientation.y = 0.0

        self.pub_goal.publish(msg)

def main(args=None):
    rclpy.init(args=args)
    node = SentryStrategyNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
